### ISSUE TITLE
Is test save_now / exit_now really working in test_builld.sh

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#133]
Dear Egor,

When I run the script `test_build.sh` in `release_branch`, when it comes to `save_now` and `exit_now` tests, I only get this output:

```
Test: save_now & exit now on  /home/niceno/Development/T-Flows-Release/Tests/Laminar/Backstep/Orthogonal
================================= TEST 1 ==============================
np=1, MPI=no
clean compile in: /home/niceno/Development/T-Flows-Release/Tests/../Sources/Process
make FORTRAN=gnu DEBUG=no CGNS_HDF5=no MPI=no
time elapsed: 15 seconds
save_now
================================= TEST 2 ==============================
np=1, MPI=yes
clean compile in: /home/niceno/Development/T-Flows-Release/Tests/../Sources/Process
make FORTRAN=gnu DEBUG=no CGNS_HDF5=no MPI=yes
time elapsed: 22 seconds
save_now
================================= TEST 3 ==============================
np=2, MPI=yes
save_now
```
Does it mean everything is OK?  I see that in the script (line around 570) you have the command:
```
echo "save_exit_now_test was successfull"
```
but it never gets executed.  Is that something to worry about?

**Comment by palkinev** [comment]
Dear Bojan,

Indeed, this **save_exit_now_test** had a bug.
According to your logs it failed without an error code.
But error itself was not related to T-Flows directly, but rather to the fact that this script was relying on verbose output in **stdout**.

I believe that this issue is resolved now.

Please, look at [this link](https://github.com/DelNov/T-Flows/pull/135) 

Best regards,
Egor
