### ISSUE TITLE
Problem with b.c. at np>1

### ISSUE THREAD

**Issue by palkinev** [DelNov/T-Flows#38]
I found out that we have some problem, when we launch any test case with np > 1. 
In `Load_Cns` after reading .cns file no all b.c. are correctly determined.

with following piece of code just after `Load_Cns` call it can be confirmed:
```
    do c = -grid % n_bnd_cells, -1
      print *, "c=",c, "color=",grid % bnd_cond % color(c)
    end do
```

checked on Channel_Re_Tau_590 and Fuel_Bundle;

in case of Channel output will tell that there is b.c. color number "10091" and it is not a random value.

This problem exist since first commit with message

> " Imported sources for the first stable release."

**Comment by Niceno** [comment]
I don't see it as a bug really.  It is simply that in the parallel version some boundary cells become buffer cells, and the color for buffer cells is: `10091`.  Have a look at the: `Sources/Shared/Bnd_Cond_Mod.f90`

**Comment by Niceno** [comment]
OK, in order to make sequential and parallel version more consistent, I remove the boundary cells which become periodic faces.  The necessary changes are in `Convert/Calculate_Geometry.f90`  It works the same as before, but the output Egor was getting before from lines:

```
    do c = -grid % n_bnd_cells, -1
      print *, "c=",c, "color=",grid % bnd_cond % color(c)
    end do
```
in `Load_Cns`, makes it more apparent that additional "rogue" boundary cells are actually buffers.
